name: Deploy Infrastructure
concurrency: WorkflowConcurrencyKey

on:
  workflow_dispatch:
  push:
    branches:
    - tutorial-04

permissions:
  id-token: write  ## Need to be able to write the ID token (i.e., ask Azure AD for token and write the response)
  contents: read   ## Need to be able to read what it creates (i.e., read what was retrieved from Azure AD)

env:
    AZURE_RESOURCEGROUP_NAME: Xyz-Tutorial-04
    ENVIRONMENT_TYPE: nonprod
    DEPLOYMENT_NAME: "GitHub-Workflow-Run-${{ github.run_number }}" ## Alphanumeric plus .-_ (i.e., `[a-zA-Z0-9.-_]+`)
    PATH_TO_BICEP_FILE: ./deploy/main-tutorial-04.bicep

jobs:

  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/job-lint-bicep.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep

  validate:
    # needs: [lint]
    uses: ./.github/workflows/job-validate-bicep.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep
      environmentType: nonprod
      resourceGroupName: Xyz-Tutorial-04
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  preview:
    needs: [lint, validate]
    uses: ./.github/workflows/job-preview-bicep.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep
      environmentType: nonprod
      resourceGroupName: Xyz-Tutorial-04
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    runs-on: ubuntu-latest
    environment: Tutorial-04      ## Environment protection rules on this environment specification in GitHub will trigger requirement for manual approval
    needs: [preview]
    uses: ./.github/workflows/job-deploy.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep
      environmentNamePrefix: Tutorial-04
      environmentType: nonprod
      resourceGroupName: Xyz-Tutorial-04
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

