name: Deploy Infrastructure
concurrency: WorkflowConcurrencyKey

on:
  workflow_dispatch:
  push:
    branches:
    - tutorial-04

permissions:
  id-token: write  ## Need to be able to write the ID token (i.e., ask Azure AD for token and write the response)
  contents: read   ## Need to be able to read what it creates (i.e., read what was retrieved from Azure AD)

env:
    AZURE_RESOURCEGROUP_NAME: Xyz-Tutorial-04
    DEPLOYMENT_NAME: "GitHub-Workflow-Run-${{ github.run_number }}" ## Alphanumeric plus .-_ (i.e., `[a-zA-Z0-9.-_]+`)
    PATH_TO_BICEP_FILE: ./deploy/main-tutorial-04.bicep

jobs:

  ## Workaround to pass non-secret env vars to jobs
  setup_vars: 
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      PATH_TO_BICEP_FILE: ${{ steps.step1.outputs.PATH_TO_BICEP_FILE }}
    steps:
      - run: echo ${{ env.PATH_TO_BICEP_FILE }}
      - name: Set Variables
        id: step1
        run: |
          echo "AZURE_RESOURCEGROUP_NAME=${{ env.AZURE_RESOURCEGROUP_NAME }}" >> $GITHUB_OUTPUT
          echo "DEPLOYMENT_NAME=${{ env.DEPLOYMENT_NAME }}" >> $GITHUB_OUTPUT
          echo "PATH_TO_BICEP_FILE=${{ env.PATH_TO_BICEP_FILE }}" >> $GITHUB_OUTPUT
      - name: Output Variables
        run: |
          echo ${{ steps.step1.outputs.AZURE_RESOURCEGROUP_NAME }}
          echo ${{ steps.step1.outputs.DEPLOYMENT_NAME }}
          echo ${{ steps.step1.outputs.PATH_TO_BICEP_FILE }}

  test_vars:
    needs: [setup_vars]
    runs-on: ubuntu-latest
    steps:
      - name: Check variables are set - AZURE_RESOURCEGROUP_NAME
        shell: bash
        env: 
          value: needs.setup_vars.outputs.AZURE_RESOURCEGROUP_NAME
        run: |
          if [ "${{ value }}" != '' ]; then
            echo "value is set";
          else
            echo >&2 "value unavailable";
            exit 1
          fi
      - name: Check variables are set - DEPLOYMENT_NAME
        shell: bash
        env: 
          value: needs.setup_vars.outputs.DEPLOYMENT_NAME
        run: |
          if [ "${{ value }}" != '' ]; then
            echo "value is set";
          else
            echo >&2 "value unavailable";
            exit 1
          fi
      - name: Check variables are set - PATH_TO_BICEP_FILE
        shell: bash
        env: 
          value: needs.setup_vars.outputs.PATH_TO_BICEP_FILE
        run: |
          if [ "${{ value }}" != '' ]; then
            echo "value is set";
          else
            echo >&2 "value unavailable";
            exit 1
          fi


  lint:
    needs: [test_vars]
    uses: ./.github/workflows/job-lint-bicep.yml
    with:
      pathToBicepFile: ${{ needs.setup_vars.outputs.PATH_TO_BICEP_FILE }}

  validate:
    needs: [test_vars]
    # needs: [lint]
    uses: ./.github/workflows/job-validate-bicep.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep
      environmentType: nonprod
      resourceGroupName: Xyz-Tutorial-04
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  preview:
    needs: [lint, validate]
    uses: ./.github/workflows/job-preview-bicep.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep
      environmentType: nonprod
      resourceGroupName: Xyz-Tutorial-04
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    needs: [preview]
    uses: ./.github/workflows/job-deploy.yml
    with:
      pathToBicepFile: ./deploy/main-tutorial-04.bicep
      environmentNamePrefix: Tutorial-04
      environmentType: nonprod
      resourceGroupName: Xyz-Tutorial-04
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TUTORIAL_04 }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

